# Generated by Django 4.2.2 on 2023-06-10 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_playlistmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='songmodel',
            old_name='duration',
            new_name='duration_seconds',
        ),
    ]
