# Generated by Django 4.2.2 on 2023-06-10 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_rename_duration_songmodel_duration_seconds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlistmodel',
            name='songs',
            field=models.ManyToManyField(blank=True, to='mainapp.songmodel'),
        ),
    ]
